### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by SvenC56** [PhantomBotDE/PhantomBotDE#19]
Detailed Description:

Hey, es wäre super wenn das Image (vllt. per Github Actions) auf Docker gepushed werden könnte. Die Dockerfile gibt es ja bereits. Es müsste also nur ein neues Docker Repo erstellt werden. 🙂 

Edit: 
Es gibt zumindest in Jenkins z.B. den "Release" Trigger, sodass er nur ein neues Image baut/ published sofern ein neuer Release hochgeladen wird.

Vielen Dank!

**Comment by vesturo** [comment]
Ich schaue mir dieses Docker zeug mal heute an :) Wir bekommen das schon irgendwie zum laufen haha

**Comment by SvenC56** [comment]
Super vielen Dank. Kann auch gerne helfen.

**Comment by vesturo** [comment]
> Super vielen Dank. Kann auch gerne helfen.

Das wäre super, bist du in unserem Discord zwecks einfachem austausch? 
Falls ja einfach mal bitte **_**[FES] Sands#9612**_** schreiben :)

**Comment by SvenC56** [comment]
Hey, 

anbei meine Änderungen:

<details>
<summary>Dockerfile</summary>

```yml
#
# Copyright (C) 2016-2019 phantombot.tv
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Build container
FROM openjdk:11.0.4-jdk as builder

ARG PROJECT_NAME=PhantomBotDE
ARG BASEDIR=/opt/${PROJECT_NAME}
ARG BUILDDIR=${BASEDIR}_build
ARG DATADIR=${BASEDIR}_data

ENV DEBIAN_FRONTEND=noninteractive
RUN mkdir -p "${BUILDDIR}" \
    && apt-get update -q \
    && apt-get install -yqq ant \
    && apt-get clean \
    && rm -rf \
    /var/lib/apt/lists/* \
    /tmp/* \
    /var/tmp/*

COPY . "${BUILDDIR}"

RUN cd "${BUILDDIR}" \
    && ant jar

# Application container
FROM azul/zulu-openjdk-alpine:11.0.4-jre

ARG PROJECT_NAME=PhantomBotDE
ARG BASEDIR=/opt/${PROJECT_NAME}
ARG BUILDDIR=${BASEDIR}_build
ARG DATADIR=${BASEDIR}_data

RUN mkdir -p "${BASEDIR}" "${DATADIR}" "${BASEDIR}/logs"

COPY --from=builder "${BUILDDIR}/dist/${PROJECT_NAME}-3.1.2/." "${BASEDIR}/"

RUN cd "${BASEDIR}" \
    && rm -rf \
    && mkdir "${DATADIR}/scripts" \
    && mkdir "${DATADIR}/scripts/custom" \
    && mkdir "${DATADIR}/scripts/discord" \
    && mkdir "${DATADIR}/scripts/lang" \
    && mv "${BASEDIR}/addons" "${DATADIR}/" \
    && mv "${BASEDIR}/config" "${DATADIR}/" \
    && mv "${BASEDIR}/logs" "${DATADIR}/" \
    && mv "${BASEDIR}/scripts/custom" "${DATADIR}/scripts/custom/" \
    && mv "${BASEDIR}/scripts/discord/custom" "${DATADIR}/scripts/discord/" \
    && mv "${BASEDIR}/scripts/lang/custom" "${DATADIR}/scripts/lang/" \
    && mkdir "${DATADIR}/dbbackup" \
    && ln -s "${DATADIR}/addons" \
    && ln -s "${DATADIR}/config" \
    && ln -s "${DATADIR}/dbbackup" \
    && ln -s "${DATADIR}/logs" \
    && ln -s "${DATADIR}/scripts/custom" "${BASEDIR}/scripts/custom" \
    && ln -s "${DATADIR}/scripts/discord" "${BASEDIR}/scripts/discord/custom" \
    && ln -s "${DATADIR}/scripts/lang" "${BASEDIR}/scripts/lang/custom"

VOLUME "${DATADIR}"

WORKDIR "${BASEDIR}"

EXPOSE 25000

CMD ["sh", "launch-service.sh"]
```

</details>

Hier war die größere Änderung den Projektnamen zu ändern: `PhantomBotDE`

In der `docker-compose.yml` Datei muss das Image entsprechend des Dockerhub Nutzers und Image Namen angepasst werden.

Zum Workflow:
Es müssen die Secrets `DOCKER_USER` und `DOCKER_PASSWORD` erstellt werden. Der Workflow wird mit jedem neuen Release triggert. Es wird automatisch der Tag herausgefunden und auf das Dockerimage gepackt. Am Ende gibt es jeweils ein `latest` und z.B. ein `v3.1.2` Tag (siehe [hier](https://hub.docker.com/r/svenc56/phantombotde/tags)).
Nightly Builds sind aktuell noch nicht konfiguriert.

<details>
<summary>.github/workflow/docker.yml</summary>

```yml
name: PhantomBotDE CI/CD
on:
  release:
    types: [published]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.DOCKER_USER }}/phantombotde
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ env.RELEASE_VERSION }}"
```

</details>

Bei Fragen gerne auf mich zukommen. 👍
